# Generated by Django 5.0.7 on 2025-07-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CIHRProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        help_text="CIHR project unique identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("project_title", models.TextField(help_text="Title of the project")),
                (
                    "principal_investigators",
                    models.TextField(
                        blank=True, help_text="Principal investigators", null=True
                    ),
                ),
                (
                    "co_investigators",
                    models.TextField(
                        blank=True, help_text="Co-investigators", null=True
                    ),
                ),
                (
                    "supervisors",
                    models.TextField(blank=True, help_text="Supervisors", null=True),
                ),
                (
                    "institution_paid",
                    models.CharField(
                        blank=True,
                        help_text="Institution receiving payment",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "research_institution",
                    models.CharField(
                        blank=True,
                        help_text="Research institution",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department", max_length=300, null=True
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True, help_text="CIHR program", max_length=300, null=True
                    ),
                ),
                (
                    "competition_year_month",
                    models.CharField(
                        blank=True,
                        help_text="Competition year/month",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "peer_review_committee",
                    models.CharField(
                        blank=True,
                        help_text="Peer review committee",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "primary_institute",
                    models.CharField(
                        blank=True,
                        help_text="Primary CIHR institute",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "primary_theme",
                    models.CharField(
                        blank=True,
                        help_text="Primary research theme",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "term_years_months",
                    models.CharField(
                        blank=True, help_text="Term duration", max_length=50, null=True
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Research keywords", null=True
                    ),
                ),
                (
                    "abstract_summary",
                    models.TextField(
                        blank=True, help_text="Abstract summary", null=True
                    ),
                ),
                (
                    "cihr_amounts",
                    models.CharField(
                        blank=True,
                        help_text="CIHR funding amounts",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cihr_equipment",
                    models.CharField(
                        blank=True,
                        help_text="CIHR equipment funding",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "external_funding_partners",
                    models.TextField(
                        blank=True, help_text="External funding partners", null=True
                    ),
                ),
                (
                    "external_funding_amounts",
                    models.CharField(
                        blank=True,
                        help_text="External funding amounts",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "broad_study_type",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("observational", "Observational"),
                            ("evidence_synthesis", "Evidence Synthesis"),
                            ("other", "Other"),
                            ("unclear", "Unclear"),
                        ],
                        default="unclear",
                        max_length=50,
                    ),
                ),
                (
                    "narrow_study_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("trial_phase", models.CharField(default="N/A", max_length=10)),
                (
                    "observational_timeframe",
                    models.CharField(default="N/A", max_length=50),
                ),
                ("justification", models.TextField(blank=True, null=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("canadian", "Canadian"),
                            ("global", "Global"),
                            ("mixed", "Mixed"),
                            ("unclear", "Unclear"),
                        ],
                        default="unclear",
                        max_length=20,
                    ),
                ),
                ("ipd_used", models.CharField(default="unclear", max_length=20)),
                ("novelty_statement", models.TextField(blank=True, null=True)),
                ("replication_study", models.CharField(default="no", max_length=10)),
                (
                    "target_population_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("age_range", models.CharField(default="unclear", max_length=50)),
                ("gender_focus", models.CharField(default="unclear", max_length=20)),
                (
                    "vulnerable_populations",
                    models.CharField(default="no", max_length=10),
                ),
                ("rare_disease", models.CharField(default="no", max_length=10)),
                ("population_description", models.TextField(blank=True, null=True)),
                (
                    "intervention_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intervention_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "control_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dose_response", models.CharField(default="no", max_length=10)),
                ("combination_therapy", models.CharField(default="no", max_length=10)),
                (
                    "personalized_medicine",
                    models.CharField(default="no", max_length=10),
                ),
                ("primary_outcome", models.TextField(blank=True, null=True)),
                (
                    "primary_outcome_type",
                    models.CharField(default="unclear", max_length=50),
                ),
                ("safety_focus", models.CharField(default="no", max_length=10)),
                ("quality_of_life", models.CharField(default="no", max_length=10)),
                ("biomarker_endpoints", models.CharField(default="no", max_length=10)),
                ("time_to_event", models.CharField(default="no", max_length=10)),
                ("composite_endpoint", models.CharField(default="no", max_length=10)),
                ("ai_machine_learning", models.CharField(default="no", max_length=10)),
                ("digital_health", models.CharField(default="no", max_length=10)),
                ("telemedicine", models.CharField(default="no", max_length=10)),
                ("wearable_technology", models.CharField(default="no", max_length=10)),
                ("big_data_analytics", models.CharField(default="no", max_length=10)),
                ("blockchain", models.CharField(default="no", max_length=10)),
                ("cost_effectiveness", models.CharField(default="no", max_length=10)),
                ("budget_impact", models.CharField(default="no", max_length=10)),
                (
                    "health_technology_assessment",
                    models.CharField(default="no", max_length=10),
                ),
                ("resource_utilization", models.CharField(default="no", max_length=10)),
                (
                    "productivity_outcomes",
                    models.CharField(default="no", max_length=10),
                ),
                (
                    "implementation_science",
                    models.CharField(default="no", max_length=10),
                ),
                ("policy_evaluation", models.CharField(default="no", max_length=10)),
                (
                    "health_system_integration",
                    models.CharField(default="no", max_length=10),
                ),
                (
                    "scalability_assessment",
                    models.CharField(default="no", max_length=10),
                ),
                (
                    "barrier_identification",
                    models.CharField(default="no", max_length=10),
                ),
                ("adaptive_design", models.CharField(default="no", max_length=10)),
                ("bayesian_methods", models.CharField(default="no", max_length=10)),
                (
                    "machine_learning_analysis",
                    models.CharField(default="no", max_length=10),
                ),
                ("novel_biostatistics", models.CharField(default="no", max_length=10)),
                (
                    "patient_reported_outcomes",
                    models.CharField(default="no", max_length=10),
                ),
                ("real_world_evidence", models.CharField(default="no", max_length=10)),
                ("industry_partnership", models.CharField(default="no", max_length=10)),
                ("patient_engagement", models.CharField(default="no", max_length=10)),
                ("community_based", models.CharField(default="no", max_length=10)),
                (
                    "indigenous_collaboration",
                    models.CharField(default="no", max_length=10),
                ),
                (
                    "international_collaboration",
                    models.CharField(default="no", max_length=10),
                ),
                (
                    "international_network",
                    models.CharField(default="no", max_length=10),
                ),
                ("regulatory_pathway", models.CharField(default="no", max_length=10)),
                ("ethics_focus", models.CharField(default="no", max_length=10)),
                ("consent_innovation", models.CharField(default="no", max_length=10)),
                ("data_sharing", models.CharField(default="no", max_length=10)),
                (
                    "therapeutic_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("disease_stage", models.CharField(default="unclear", max_length=50)),
                ("comorbidity_focus", models.CharField(default="no", max_length=10)),
                ("pandemic_related", models.CharField(default="no", max_length=10)),
                ("environmental_health", models.CharField(default="no", max_length=10)),
                ("social_determinants", models.CharField(default="no", max_length=10)),
                ("health_equity", models.CharField(default="no", max_length=10)),
                ("climate_health", models.CharField(default="no", max_length=10)),
                ("urban_rural", models.CharField(default="unclear", max_length=20)),
                ("biobank_use", models.CharField(default="no", max_length=10)),
                ("registry_linkage", models.CharField(default="no", max_length=10)),
                ("cohort_establishment", models.CharField(default="no", max_length=10)),
                ("platform_trial", models.CharField(default="no", max_length=10)),
                ("study_duration", models.CharField(default="unclear", max_length=20)),
                ("multicenter", models.CharField(default="no", max_length=10)),
                (
                    "healthcare_setting",
                    models.CharField(default="unclear", max_length=50),
                ),
                ("disease_area", models.TextField(blank=True, null=True)),
                ("methodology_innovation", models.TextField(blank=True, null=True)),
                (
                    "knowledge_translation_focus",
                    models.CharField(default="no", max_length=10),
                ),
                (
                    "equity_considerations",
                    models.CharField(default="no", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cihr_projects",
                "ordering": ["-project_id"],
                "indexes": [
                    models.Index(
                        fields=["project_id"], name="cihr_projec_project_a5099b_idx"
                    ),
                    models.Index(
                        fields=["broad_study_type"],
                        name="cihr_projec_broad_s_edfe7d_idx",
                    ),
                    models.Index(
                        fields=["therapeutic_area"],
                        name="cihr_projec_therape_ad7409_idx",
                    ),
                    models.Index(
                        fields=["primary_institute"],
                        name="cihr_projec_primary_524d87_idx",
                    ),
                    models.Index(
                        fields=["primary_theme"], name="cihr_projec_primary_5ecd13_idx"
                    ),
                    models.Index(
                        fields=["competition_year_month"],
                        name="cihr_projec_competi_e2469b_idx",
                    ),
                ],
            },
        ),
    ]
