# Generated by Django 5.2.4 on 2025-07-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cihrproject",
            name="adaptive_design",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="ai_machine_learning",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="barrier_identification",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="bayesian_methods",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="big_data_analytics",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="biobank_use",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="biomarker_endpoints",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="blockchain",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="budget_impact",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="climate_health",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="cohort_establishment",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="combination_therapy",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="community_based",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="comorbidity_focus",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="competition_year_month",
            field=models.CharField(
                blank=True, help_text="Competition year/month", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="composite_endpoint",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="consent_innovation",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="control_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="cost_effectiveness",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="data_sharing",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="digital_health",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="dose_response",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="environmental_health",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="equity_considerations",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="ethics_focus",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="health_equity",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="health_system_integration",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="health_technology_assessment",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="implementation_science",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="indigenous_collaboration",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="industry_partnership",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="international_collaboration",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="international_network",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="ipd_used",
            field=models.CharField(default="unclear", max_length=50),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="knowledge_translation_focus",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="machine_learning_analysis",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="multicenter",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="novel_biostatistics",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="pandemic_related",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="patient_engagement",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="patient_reported_outcomes",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="personalized_medicine",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="platform_trial",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="policy_evaluation",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="productivity_outcomes",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="quality_of_life",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="rare_disease",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="real_world_evidence",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="registry_linkage",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="regulatory_pathway",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="replication_study",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="resource_utilization",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="safety_focus",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="scalability_assessment",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="social_determinants",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="telemedicine",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="time_to_event",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="trial_phase",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="vulnerable_populations",
            field=models.CharField(default="no", max_length=20),
        ),
        migrations.AlterField(
            model_name="cihrproject",
            name="wearable_technology",
            field=models.CharField(default="no", max_length=20),
        ),
    ]
